import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({

    state: {
        betties: 150,
        betHistory: [],
        event: {},

        events: [{
                name: "G2 Esports VS MAD Lions",
                start: "2021-01-22 18:00",
                end: "2021-01-22 19:00",
                id: 1,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Astralis VS SK Gaming",
                start: "2021-01-22 19:00",
                end: "2021-01-22 20:00",
                id: 2,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },

            },
            {
                name: "Rogue VS EXCEL",
                start: "2021-01-22 20:00",
                end: "2021-01-22 21:00",
                id: 3,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 1.8,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Team Vitality VS Schalke 04",
                start: "2021-01-22 21:00",
                end: "2021-01-22 22:00",
                id: 4,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 1.8,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },

            },
            {
                name: "Misfits Gaming VS Fnatic",
                start: "2021-01-22 22:00",
                end: "2021-01-22 23:00",
                id: 5,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Schalke 04 VS EXCEL",
                start: "2021-01-23 17:00",
                end: "2021-01-22 18:00",
                id: 6,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 4,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Team Vitality VS Misfits Gaming",
                start: "2021-01-23 18:00",
                end: "2021-01-22 19:00",
                id: 7,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "MAD Lions VS Astralis",
                start: "2021-01-23 19:00",
                end: "2021-01-22 20:00",
                id: 8,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "SK Gaming VS G2 Esports",
                start: "2021-01-23 20:00",
                end: "2021-01-22 21:00",
                id: 9,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },

            },
            {
                name: "Fnatic VS Rogue",
                start: "2021-01-23 21:00",
                end: "2021-01-22 22:00",
                id: 10,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 1.8,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Astralis VS Team Vitality",
                start: "2021-01-24 17:00",
                end: "2021-01-24 18:00",
                id: 11,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Rogue VS SK Gaming",
                start: "2021-01-24 18:00",
                end: "2021-01-24 19:00",
                id: 12,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 1.8,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Misfits Gaming VS MAD Lions",
                start: "2021-01-24 19:00",
                end: "2021-01-24 20:00",
                id: 13,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Fnatic VS Schalke 04",
                start: "2021-01-24 20:00",
                end: "2021-01-24 21:00",
                id: 14,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 4,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "EXCEL VS G2 Esports",
                start: "2021-01-24 21:00",
                end: "2021-01-24 22:00",
                id: 15,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "MAD Lions VS EXCEL",
                start: "2021-01-29 18:00",
                end: "2021-01-29 19:00",
                id: 16,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Schalke 04 VS SK Gaming",
                start: "2021-01-29 19:00",
                end: "2021-01-29 20:00",
                id: 17,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 4,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "G2 Esports VS Astralis",
                start: "2021-01-29 20:00",
                end: "2021-01-29 21:00",
                id: 18,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Misfits Gaming VS Rogue",
                start: "2021-01-29 21:00",
                end: "2021-01-29 22:00",
                id: 19,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 1.8,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Team Vitality VS Fnatic",
                start: "2021-01-29 22:00",
                end: "2021-01-29 23:00",
                id: 20,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "EXCEL VS Astralis",
                start: "2021-01-30 17:00",
                end: "2021-01-30 18:00",
                id: 21,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Team Vitality VS Rogue",
                start: "2021-01-30 18:00",
                end: "2021-01-30 19:00",
                id: 22,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 1.8,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Misfits Gaming VS SK Gaming",
                start: "2021-01-30 19:00",
                end: "2021-01-30 20:00",
                id: 23,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Schalke 04 VS G2 Esports",
                start: "2021-01-30 20:00",
                end: "2021-01-30 21:00",
                id: 24,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 4,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Fnatic VS MAD Lions",
                start: "2021-01-30 21:00",
                end: "2021-01-30 22:00",
                id: 25,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Schalke 04 VS Rogue",
                start: "2021-02-5 18:00",
                end: "2021-02-5 19:00",
                id: 26,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 1.8,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 2,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Misfits Gaming VS EXCEL",
                start: "2021-02-5 19:00",
                end: "2021-02-5 20:00",
                id: 27,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Team Vitality VS G2 Esports",
                start: "2021-02-5 20:00",
                end: "2021-02-5 21:00",
                id: 28,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "MAD Lions VS SK Gaming",
                start: "2021-02-5 21:00",
                end: "2021-02-5 22:00",
                id: 29,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Fnatic VS Astralis",
                start: "2021-02-5 22:00",
                end: "2021-02-5 23:00",
                id: 30,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "EXCEL VS SK Gaming",
                start: "2021-02-6 17:00",
                end: "2021-02-6 18:00",
                id: 31,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Schalke 04 VS Misfits Gaming",
                start: "2021-02-6 18:00",
                end: "2021-02-6 19:00",
                id: 32,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 1.8,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },

            },
            {
                name: "Team Vitality VS MAD Lions",
                start: "2021-02-6 19:00",
                end: "2021-02-6 20:00",
                id: 33,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Rogue VS Astralis",
                start: "2021-02-6 20:00",
                end: "2021-02-6 21:00",
                id: 34,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 2,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "G2 Esports VS Fnatic",
                start: "2021-02-6 21:00",
                end: "2021-02-6 22:00",
                id: 35,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Team Vitality VS SK Gaming",
                start: "2021-02-12 18:00",
                end: "2021-02-12 19:00",
                id: 36,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Schalke 04 VS MAD Lions",
                start: "2021-02-12 19:00",
                end: "2021-02-12 20:00",
                id: 37,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 1.8,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Misfits Gaming VS Astralis",
                start: "2021-02-12 20:00",
                end: "2021-02-12 21:00",
                id: 38,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Fnatic VS EXCEL",
                start: "2021-02-12 21:00",
                end: "2021-02-12 22:00",
                id: 39,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "G2 Esports VS Rogue",
                start: "2021-02-12 22:00",
                end: "2021-02-12 23:00",
                id: 40,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 2,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Team Vitality VS EXCEL",
                start: "2021-02-13 17:00",
                end: "2021-02-13 18:00",
                id: 41,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Schalke 04 VS Astralis",
                start: "2021-02-13 18:00",
                end: "2021-02-13 19:00",
                id: 42,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 1.8,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Fnatic VS SK Gaming",
                start: "2021-02-13 19:00",
                end: "2021-02-13 20:00",
                id: 43,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "MAD Lions VS Rogue",
                start: "2021-02-13 20:00",
                end: "2021-02-13 21:00",
                id: 44,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 2,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Misfits Gaming VS G2 Esports",
                start: "2021-02-13 21:00",
                end: "2021-02-13 22:00",
                id: 45,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Schalke 04 VS SK Gaming",
                start: "2021-02-19 18:00",
                end: "2021-02-19 19:00",
                id: 46,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FSchalke04_FullColor.png",
                    cote: 1.8,
                    id: 1,
                    name: "Schalke 04",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/SK_Gaming_logo.svg/220px-SK_Gaming_logo.svg.png",
                    cote: 2,
                    id: 8,
                    name: "SK Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "MAD Lions VS EXCEL",
                start: "2021-02-19 19:00",
                end: "2021-02-19 20:00",
                id: 47,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591395339_MadLionsMAD-01-FullonDark.png",
                    cote: 4,
                    id: 7,
                    name: "MAD Lions",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Excel_Esports_logo.png/220px-Excel_Esports_logo.png",
                    cote: 1.8,
                    id: 4,
                    name: "Excel Esport",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },

            },
            {
                name: "Misfits Gaming VS Rogue",
                start: "2021-02-19 20:00",
                end: "2021-02-19 21:00",
                id: 48,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591419157_MisfitsMSF-01-FullonDark.png",
                    cote: 4,
                    id: 3,
                    name: "Misfits Gaming",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Rogue_logo.svg/220px-Rogue_logo.svg.png",
                    cote: 2,
                    id: 2,
                    name: "Rogue",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "Team Vitality VS Fnatic",
                start: "2021-02-19 21:00",
                end: "2021-02-19 22:00",
                id: 49,
                team1: {
                    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Logo_Team_Vitality_2020.png",
                    cote: 1.8,
                    id: 5,
                    name: "Team Vitality",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2F1592591295307_FnaticFNC-01-FullonDark.png",
                    cote: 4,
                    id: 9,
                    name: "Fnatic",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            },
            {
                name: "G2 Esports VS Astralis",
                start: "2021-02-19 22:00",
                end: "2021-02-19 23:00",
                id: 50,
                team1: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FG2_FullColor2.png",
                    cote: 2,
                    id: 6,
                    name: "G2 Esports",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
                team2: {
                    logo: "https://am-a.akamaihd.net/image/?resize=70:&f=http%3A%2F%2Fstatic.lolesports.com%2Fteams%2FAstralis_FullColor.png",
                    cote: 2,
                    id: 10,
                    name: "Astralis",
                    history: [
                        { result: "W" },
                        { result: "W" },
                        { result: "L" },
                        { result: "W" },
                        { result: "L" },
                    ],
                },
            }
        ]
    },


    mutations: {
        addBetties(state, amount) {
            state.betties += amount;
        },
        removeBetties(state, amount) {
            state.betties -= amount;
        },
        addBetToHistory(state, bet) {
            state.betHistory = [...state.betHistory, bet];
        },

        setEvent(state, event) {
            state.event = event;
        }

    },

    actions: {
        betAction({ commit }, { bet }) {
            commit("addBetToHistory", bet);
            commit("removeBetties", bet.amount);
        },

        getEventId({ commit, state }, eventId) {
            state.events.forEach(event => {
                if (event.id == eventId) {
                    commit("setEvent", event);
                }
            });
        }

    },


    modules: {},
});